name: docker-php-nginx-postgres-composer

services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
    
    php:
        build: .docker
        restart: always
        environment:
            - DB_DRIVER=pgsql
            - DB_HOST=postgres
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
        depends_on:
            - postgres
    
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    
    postgres:
        image: postgres:17
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: