name: app

services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
    
    php:
        build: .docker
        restart: always
        environment:
            - DB_DRIVER=pgsql
            # - DB_DRIVER=mysql
            - DB_HOST=pgsql
            # - DB_HOST=mysql
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
        depends_on:
            - pgsql
            # - mysql
    
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    
    pgsql:
        image: postgres:17
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - pgsql_data:/var/lib/postgresql/data

    # mysql:
    #     image: mysql:9
    #     restart: always
    #     environment:
    #         - MYSQL_DATABASE=${DB_NAME}
    #         - MYSQL_USER=${DB_USER}
    #         - MYSQL_PASSWORD=${DB_PASSWORD}
    #         - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - mysql_data:/var/lib/mysql

volumes:
    pgsql_data:
    # mysql_data: